// <auto-generated />
using System;
using AdopcionOnline.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130202915_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Imagen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.CategoriaEdad", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasEdad");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Nombre = "Cachorro"
                        },
                        new
                        {
                            Id = (byte)2,
                            Nombre = "Joven"
                        },
                        new
                        {
                            Id = (byte)3,
                            Nombre = "Adulto"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.CategoriaGenero", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasGenero");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Nombre = "Hembra"
                        },
                        new
                        {
                            Id = (byte)2,
                            Nombre = "Macho"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.CategoriaPersonalidad", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaPersonalidades");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Nombre = "Juguetón"
                        },
                        new
                        {
                            Id = (byte)2,
                            Nombre = "Tranquilo"
                        },
                        new
                        {
                            Id = (byte)3,
                            Nombre = "Protector"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.CategoriaTipoAnimal", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasTipoAnimal");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Nombre = "Perro"
                        },
                        new
                        {
                            Id = (byte)2,
                            Nombre = "Gato"
                        },
                        new
                        {
                            Id = (byte)3,
                            Nombre = "Conejo"
                        },
                        new
                        {
                            Id = (byte)4,
                            Nombre = "Ave"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("bit");

                    b.Property<byte>("CategoriaEdadId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("CategoriaGeneroId")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("CategoriaTipoAnimalId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionCorta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionLarga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<byte>("EdadMeses")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TamanioId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TipoAnimalId")
                        .HasColumnType("tinyint");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaEdadId");

                    b.HasIndex("CategoriaGeneroId");

                    b.HasIndex("CategoriaTipoAnimalId");

                    b.HasIndex("TamanioId");

                    b.HasIndex("TipoAnimalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.MascotaPersonalidad", b =>
                {
                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<byte>("CategoriaPersonalidadId")
                        .HasColumnType("tinyint");

                    b.HasKey("MascotaId", "CategoriaPersonalidadId");

                    b.HasIndex("CategoriaPersonalidadId");

                    b.ToTable("MascotaPersonalidades");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.Tamanio", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("TamanioMascota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tamanio");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.Mascota", b =>
                {
                    b.HasOne("Domain.Entities.Mascotas.CategoriaEdad", "CategoriaEdad")
                        .WithMany("Mascotas")
                        .HasForeignKey("CategoriaEdadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mascotas.CategoriaGenero", "CategoriaGenero")
                        .WithMany("Mascotas")
                        .HasForeignKey("CategoriaGeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mascotas.CategoriaTipoAnimal", null)
                        .WithMany("Mascotas")
                        .HasForeignKey("CategoriaTipoAnimalId");

                    b.HasOne("Domain.Entities.Mascotas.Tamanio", "Tamanio")
                        .WithMany("Mascotas")
                        .HasForeignKey("TamanioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mascotas.CategoriaTipoAnimal", "CategoriaTipoAnimal")
                        .WithMany()
                        .HasForeignKey("TipoAnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Mascotas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaEdad");

                    b.Navigation("CategoriaGenero");

                    b.Navigation("CategoriaTipoAnimal");

                    b.Navigation("Tamanio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.MascotaPersonalidad", b =>
                {
                    b.HasOne("Domain.Entities.Mascotas.CategoriaPersonalidad", "CategoriaPersonalidad")
                        .WithMany("MascotaPersonalidades")
                        .HasForeignKey("CategoriaPersonalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mascotas.Mascota", "Mascota")
                        .WithMany("MascotaPersonalidades")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPersonalidad");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.CategoriaEdad", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.CategoriaGenero", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.CategoriaPersonalidad", b =>
                {
                    b.Navigation("MascotaPersonalidades");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.CategoriaTipoAnimal", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.Mascota", b =>
                {
                    b.Navigation("MascotaPersonalidades");
                });

            modelBuilder.Entity("Domain.Entities.Mascotas.Tamanio", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Mascotas");
                });
#pragma warning restore 612, 618
        }
    }
}
